name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Generate keystore
        run: |
          keytool -genkeypair -v -keystore fotocaap-release.keystore \
            -alias fotocaap -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass "Fotocaap2026Store" \
            -keypass "Fotocaap2026Key" \
            -dname "CN=Fotocaap, OU=Fotocaap, O=Fotocaap, L=Tehran, S=Tehran, C=IR"
          base64 -w0 fotocaap-release.keystore > keystore_base64.txt

      - name: Upload keystore file
        uses: actions/upload-artifact@v4
        with:
          name: fotocaap-keystore
          path: fotocaap-release.keystore

      - name: Upload base64 text
        uses: actions/upload-artifact@v4
        with:
          name: keystore-base64
          path: keystore_base64.txt
